word_list1 = [
  'gigantic' ,
  'giggle' ,
  'wobbly' ,
  'sparkly' ,
  'dash' ,
  'burrow' ,
  'mystery' ,
  'treasure' ,
  'rumble' ,
  'flutter' ,
  'comfort' ,
  'curious' ,
  'imagine' ,
  'invent' ,
]

word_list2 = [
'intriguing',
'serene',
'precise',
'fragile',
'consequence',
'intricate',
'astonished',
'navigate',
'humorous',
'enthusiastic',
'conception',
'melancholy',
'perseverance',
'fragrance',
'astonishing' ,
]

word_list3 = [
'ephemeral',
'conundrum',
'tenacious',
'exacerbate',
'venerated',
'ambiguous',
'serendipity',
'paradigm',
'mellifluous',
'stoic',
'implausible',
'indelible',
'quandary',
'eloquent',
'precipitous'
]

word_meaning = {
"gigantic" : 'extremely large or enormous.' ,
"giggle" : 'to laugh in a light, high-pitched way.' , 
"wobbly" : 'unsteady or likely to fall.' ,
"sparkly" : 'shining brightly with small flashes of light.' ,
"dash" : 'to move suddenly and quickly.' ,
"burrow" : 'to dig a hole in the ground to live in.' ,
"mystery" : 'something that is difficult to understand or explain.' ,
"treasure" : 'something valuable or precious.' ,
"rumble" : 'to make a deep, continuous sound. ' ,
"flutter" : 'to move the wings quickly, especially before flying.' ,
"comfort" : 'a feeling of peace and happiness.' ,
"curious" : 'eager to know or learn something.' ,
"imagine" : 'to form a picture in your mind of something that is not real or present.' ,
"invent" :'to create something new.' ,
"intriguing" : 'very interesting or exciting.',
"serene" : 'calm and peaceful.',
"precise" : 'exactly correct or accurate.',
"fragile" : 'delicate and easily broken.',
"consequence" : 'the result or effect of something.',
"intricate" : 'very complex or detailed.',
"astonished" : 'extremely surprised.',
"navigate" : 'to find your way around a place.',
"humorous" : 'funny or amusing.',
"enthusiastic" : 'full of enthusiasm or excitement.',
"conception" : 'an idea or plan in its early stages.',
"melancholy" : 'a feeling of sadness or pensive longing.',
"perseverance" : 'continued effort despite difficulties.',
"fragrance" : 'a pleasant smell.',
"astonishing" : 'extremely surprising.' ,
"ephemeral" : 'lasting for a very short time.',
"conundrum" : 'a confusing and difficult problem.',
"tenacious" : 'holding on firmly and not giving up.',
"exacerbate" : 'to make something worse.',
"venerated" : 'deeply respected.',
"ambiguous" : 'open to more than one interpretation.',
"serendipity" : 'the occurrence and development of events by chance in a happy or beneficial way.',
"paradigm" : 'a typical example or pattern.',
"mellifluous" : 'pleasant and soothing to hear.',
"stoic" : 'calm and unemotional.',
"implausible" : 'difficult to believe.',
"indelible" : 'leaving a permanent mark or impression.',
"quandary" : 'a state of perplexity or doubt.',
"eloquent" : 'speaking fluently and persuasively.',
"precipitous" : 'done with too much haste or without enough care.'
}